import type { Project, Task, Team, User } from "@/types";

export const mockProjects: Project[] = [
  {
    id: 1,
    name: "Client Portal Redesign",
    description: "Refresh the customer workspace and improve conversion on trial accounts.",
    status: "In Progress",
    priority: "High",
    dueDate: "2026-04-18",
    teamId: 1,
    progress: 68,
    owner: "Amina Hassan",
    tags: ["Design", "Growth"],
  },
  {
    id: 2,
    name: "Billing Automation",
    description: "Reduce manual invoicing and unify payment event handling.",
    status: "Planning",
    priority: "Medium",
    dueDate: "2026-05-03",
    teamId: 3,
    progress: 24,
    owner: "Daniel Kimani",
    tags: ["Finance", "Backend"],
  },
  {
    id: 3,
    name: "Mobile Analytics",
    description: "Instrument feature usage across iOS and Android releases.",
    status: "At Risk",
    priority: "High",
    dueDate: "2026-04-11",
    teamId: 2,
    progress: 52,
    owner: "Lina Patel",
    tags: ["Data", "Mobile"],
  },
  {
    id: 4,
    name: "Support Ops Dashboard",
    description: "Build a shared command center for tickets, SLAs, and escalations.",
    status: "Completed",
    priority: "Low",
    dueDate: "2026-03-22",
    teamId: 4,
    progress: 100,
    owner: "Musa Odhiambo",
    tags: ["Operations"],
  },
];

export const mockTasks: Task[] = [
  {
    id: 101,
    title: "Implement Zustand store for global drag state",
    status: "Backlog",
    priority: "High",
    projectId: 1,
    assigneeId: "u1",
    assigneeIds: ["u1"],
    dueDate: "2026-04-03",
    type: "Feature",
    ticket: "FE-091",
    createdById: "u1",
    description:
      "Create a shared drag state pattern so cards can move predictably across lanes and survive interaction edge cases.",
    attachments: [
      {
        id: "att-101",
        name: "drag-state-outline.pdf",
        sizeLabel: "1.2 MB",
        addedById: "u1",
        addedAt: "2026-03-30T08:00:00.000Z",
      },
    ],
    comments: [
      {
        id: "com-101",
        authorId: "u3",
        body: "Let’s keep the state shape small so we can sync it later with the API without a big refactor.",
        createdAt: "2026-03-31T07:45:00.000Z",
      },
    ],
  },
  {
    id: 102,
    title: "Setup Firebase persistence layer with offline support",
    status: "Backlog",
    priority: "Medium",
    projectId: 2,
    assigneeId: "u2",
    assigneeIds: ["u2"],
    dueDate: "2026-04-09",
    type: "Infrastructure",
    ticket: "FE-092",
    createdById: "u4",
    description:
      "Support a reliable offline draft layer so task movement and updates can recover when connectivity drops.",
    attachments: [],
    comments: [],
  },
  {
    id: 103,
    title: "Build optimistic UI wrapper component",
    status: "In Progress",
    priority: "High",
    projectId: 1,
    assigneeId: "u3",
    assigneeIds: ["u3"],
    dueDate: "2026-04-14",
    type: "Feature",
    ticket: "FE-088",
    createdById: "u1",
    description:
      "Wrap optimistic task updates so the UI feels immediate while server synchronization happens in the background.",
    attachments: [
      {
        id: "att-103",
        name: "optimistic-flow.fig",
        sizeLabel: "860 KB",
        addedById: "u3",
        addedAt: "2026-03-31T09:10:00.000Z",
      },
    ],
    comments: [
      {
        id: "com-103",
        authorId: "u2",
        body: "I’ll wire this into the RTK Query mutation path once the server update endpoint is ready.",
        createdAt: "2026-03-31T09:25:00.000Z",
      },
    ],
  },
  {
    id: 104,
    title: "Resolve sync conflict on rapid consecutive drops",
    status: "In Progress",
    priority: "High",
    projectId: 3,
    assigneeId: "u4",
    assigneeIds: ["u2", "u1"],
    dueDate: "2026-04-05",
    type: "Bugfix",
    ticket: "FE-089",
    createdById: "u4",
    description:
      "Prevent duplicate state writes when multiple drag events fire quickly during rapid user interaction.",
    attachments: [],
    comments: [
      {
        id: "com-104",
        authorId: "u1",
        body: "This one is blocking smooth demos, so let’s keep it visible in the active lane.",
        createdAt: "2026-03-31T10:00:00.000Z",
      },
    ],
  },
  {
    id: 105,
    title: "Audit border-radius consistency across desktop viewports",
    status: "Review",
    priority: "Medium",
    projectId: 1,
    assigneeId: "u2",
    assigneeIds: ["u2"],
    dueDate: "2026-04-07",
    type: "Design System",
    ticket: "FE-085",
    createdById: "u3",
    description:
      "Review visual consistency before handoff so the board feels intentional across desktop and tablet breakpoints.",
    attachments: [],
    comments: [],
  },
];

export const mockUsers: User[] = [
  { id: "u1", name: "Amina Hassan", email: "amina@saasmanager.dev", role: "Product Manager" },
  { id: "u2", name: "Daniel Kimani", email: "daniel@saasmanager.dev", role: "Frontend Engineer" },
  { id: "u3", name: "Lina Patel", email: "lina@saasmanager.dev", role: "Designer" },
  { id: "u4", name: "Musa Odhiambo", email: "musa@saasmanager.dev", role: "Operations Lead" },
];

export const mockTeams: Team[] = [
  { id: 1, name: "Growth", description: "Activation, onboarding, and user journeys", memberCount: 6 },
  { id: 2, name: "Insights", description: "Analytics, reporting, and experimentation", memberCount: 4 },
  { id: 3, name: "Platform", description: "Payments, infrastructure, and core services", memberCount: 8 },
  { id: 4, name: "Operations", description: "Support workflows and internal tooling", memberCount: 5 },
];
